thephpleague/climate

README.md
It was showing github releases, not regular git tags (how most releases are done)
=> Fixed the Latest Version badge

index.md
It was showing github releases, not regular git tags (how most releases are done)
Related to #39
=> [Documentation] Fixed the Latest Version badge

src/Util/Writer/Buffer.php, src/Util/Writer/StdErr.php, src/Util/Writer/StdOut.php, src/Util/Writer/WriterInterface.php, tests/BufferTest.php
* StdErr (to go with StdOut, related to #37)
* Buffer (to stash content for using later, would help with #44 and #55)
Example usage:
```php
use League\CLImate\Util\Writer\Buffer;
use League\CLImate\Util\Output;
$buffer = new Buffer;
$climate->setOutput(new Output($buffer));
$climate->out("Don't output me");
$climate->out("Or me");
file_put_contents("/tmp/climate.log", $buffer->get());
```
Would result in `/tmp/climate.log` containing:
```
Don't output me
Or me
```
=> Create some more standard Writer classes

src/TerminalObject/Dynamic/Input.php, tests/InputTest.php
Before this patch, if you didn't enter an acceptable response (in non-strict mode) you'd get:
How you doin? [Fine/OK] Great
How you doin? [fine/ok]
The second prompt shows the acceptable input lowercased instead of the original provided acceptable input casing.
=> Prompts for inputs won't change case if first input is not accepted

src/TerminalObject/Dynamic/Input.php, src/Util/Reader/ReaderInterface.php, src/Util/Reader/Stdin.php, tests/InputTest.php, tests/TestBase.php
This add the ability to read multiple lines of input terminated
by `^D` (`\x04` or EOT).
Additionally, this solves the issue where CLImate is unable to
read after `STDIN` hits an EOF by lazily creating a new `php://input`
stream as needed.
```php
$input = $this->cli->input('>>>', $this->reader);
$input->multiLine();
$response = $input->prompt(); // Will wait for ^D before returning
```
=> Add multi-line input support

src/TerminalObject/Dynamic/Progress.php
I noticed when debugging that the progress bar is redrawn even when there is no change:
```php
$progressBar = $climate->progress(10000);
for ($i = 0; $i <= 10000; $i++) {
$progressBar->current($i);
}
```
Currently this would re-draw the status bar 10000 times, with this patch it will only draw it 100 times.
The patch also will redraw if the label has changed, so maximum number of redraws is 100 + the number of sequentially non-unique labels, vs simply the number of times `->current()` is called.
=> Don't redraw the progress bar unnecessarily

.travis.yml
* Use `composer update` to test against the highest dependencies
* Also test against the lowest supported dependencies
* Use `travis_retry` for the composer commands (in case they fail due to an intermittent connectivity issue)
=> A bunch of stuff for Travis CI

src/TerminalObject/Helper/Art.php
The phar stream wrapper do not support glob (http://php.net/manual/de/phar.using.stream.php#104320), so I refactored the function "fileSearch" to use climate inside phar-archive.
=> Refactoring "fileSearch" - Removed "glob" for usage in phar-archives

_layouts/default.html
The https version of the documentation [is indexed](https://www.dropbox.com/s/vabwfvrfokbf238/Screenshot%202017-06-23%2015.23.53.png?dl=0), and since the references are pointing to http, the site looks broken.
=> Fix to static resources on HTTPS version

.travis.yml, README.md
It looks like the build is currently failing on HHVM, and there's been a shift in the PHP community recently to drop support for HHVM now that PHP 7 has reduced the performance gains offered by HHVM.
Also a minor update to the readme to ensure the supported versions listed are accurate
=> Drop support for HHVM

src/TerminalObject/Dynamic/Progress.php, tests/ProgressTest.php
While working on #97 I noticed that weird things happen if you aren't consistent with labels. The current code expects that either every iteration of a progress bar has a label, or none of them do.
I'm not sure if this was intended behaviour or not. But this pr allows labels to be added/removed on demand, and ensures that if a label had ever been added before, then it will be cleared if none is provided on future iterations.
Example test script to demonstrate the issue:
``` php
$climate->out('Output before progress bar.');
$progress = $climate->progress()->total(100);
for ($i = 0; $i <= 50; $i++) {
$progress->current($i, "label for nr. $i");
usleep(20000);
}
for ($i = 51; $i <= 100; $i++) {
$progress->current($i);
usleep(20000);
}
$climate->out('Output after progress bar.');
```
=> Allow labels to be shown/hidden on each iteration

src/TerminalObject/Dynamic/Progress.php, tests/ProgressTest.php
Problem: I needed to constantly repeat and lookup the same boilerplate to have a progress bar on simple loops. 
Solution: I have added some shortcut functionality to the Progress Terminal Object to be able to draw a progress bar for a loop while reducing the amount of overhead.
```
// Before
$superheroes = ['batman', 'superman', 'aquaman'];
$progress = new \CLImate::progress();
$progress->total(count($superheroes));
foreach ($superheroes as $superhero) {
echo "{$superhero} saves the day";
$progress->advance();
}
---
//After
$superheroes = ['batman', 'superman', 'aquaman'];
\CLImate::progress()->each($superheroes, function ($superhero) {
echo "{$superhero} saves the day";
});
=> added the each method to the progress class

src/TerminalObject/Basic/Json.php
No need to escape slashes in JSON data outputs as we're not dealing with HTML.
=> Add JSON_UNESCAPED_SLASHES to json_encode

src/Argument/Argument.php, src/Argument/Filter.php, src/Argument/Manager.php, src/Argument/Summary.php, tests/ArgumentTest.php
This essentially allows parsing multiple arguments with the same identifier.
For example `bin/myapp -d foo=bar -d baz=qux` would be parseable via `$climate->arguments->getArray("d")` and return `["foo=bar", "baz=qux"]`.
This is in general much more friendly than having to comma separate an options list or such like `bin/myapp -d foo=bar,baz=qux`, which typically needs more complicated handling to also assemble the options when passing them programmatically.
For backwards compatibility, the behavior of `get()` is fully retained, it will still return the argument which was passed last. Apart from the internal Argument class, nothing should have changed with regards to BC.
=> Add support for parsing multiply passed args

src/TerminalObject/Dynamic/Confirm.php, tests/ConfirmTest.php
Changed the behaviour of `confirm(...)` to accept more answers.
The following answers would now be considered valid:
- y
- n
- yes
- no
- Y
- N
- YES
- NO
=> [Enhancement] Improved the confirmation dialog

src/TerminalObject/Dynamic/Radio.php, tests/RadioTest.php
This commit let you press "Enter" directly to select an option. Just overriding "handleCharacter" and "promptFormatted" so you don't have to press "Space" _then_ "Enter".
=> Radio system improvement

src/Argument/Manager.php, src/Argument/Parser.php, tests/Argument/ManagerTest.php
When using trailing arguments to pass remaining info on to another command, it would be helpful to have the arguments preserved as an array rather than a concatenated string. This pull request adds a new method to the Manager and Parser class for accessing trailing arguments as an array. It does not modify how the string value is currently handled for trailing arguments, since that would be a backwards compatibility break and require an appropriate semver increment. In the future, these duplicate values could be merged (and trailing arguments properly escaped before concatenation) as part of a backwards-incompatible change in the next major version.
If you would like me to resubmit without duplicating the properties, please let me know. I just thought I'd submit the most compatible change …
=> Add a method to access trailing args as array

Dockerfile, composer.json, phpunit.xml, tests/Animation/AnimationTest.php, tests/AnsiTest.php, tests/Argument/ManagerTest.php, tests/BorderTest.php, tests/BrTest.php, tests/CLImateTest.php, tests/ClearTest.php, tests/ColumnTest.php, tests/DrawTest.php, tests/DumpTest.php, tests/FileTest.php, tests/FlankTest.php, tests/InlineTest.php, tests/InputTest.php, tests/LoggerTest.php, tests/OutputTest.php, tests/PaddingTest.php, tests/ProgressTest.php, tests/SleeperTest.php, tests/StyleTest.php, tests/TabTest.php, tests/TableTest.php, tests/TerminalObject/Basic/ClearLineTest.php, tests/TerminalObject/Basic/JsonTest.php, tests/TerminalObject/Dynamic/SpinnerTest.php, tests/TerminalObjectTest.php, tests/TestBase.php
- PhpUnit upgraded to 9.5.0
- Annotation `@doesNotPerformAssertions` added to tests that have no assertions.
- Removed `syntaxCheck` attribute from phpunit.xml as this is no longer a valid attribute.
=> Update PHPUnit to 9.5

src/Util/System/Linux.php
`Util/System/Linux::systemHasAnsiSupport()` throws an error in the cases where the constant STDOUT is undefined.
Fixed `systemHasAnsiSupport()` to return false in this instance.
Closes: #172
See: https://stackoverflow.com/questions/17769041/notice-use-of-undefined-constant-stdout-assumed-stdout/28898174
=> Fixed: systemHasAnsiSupport() throws an error when STDOUT is not defined

src/TerminalObject/Basic/BasicTerminalObject.php
If we do not pass the 2nd argument in border (php 8.1).
```php 
$climate->border('-');
```
=> PHP Deprecated:  strlen(): Passing null to parameter #1 (php 8.1)
